### ISSUE TITLE
Trouble reproducing public MOT20 results

### ISSUE THREAD

**Issue by JLJ19** [noahcao/OC_SORT#10]
Thanks for sharing your work.  I modified your run_ocsort_public script to run on the detection files from MOT20-train. Your code ran fine, but the tracking results seem very poor (combined HOTA = 10.7, combined MOTA = 3.4).  In general I would like to use your code with a MOT-style det.txt file, but I am concerned that it is not currently working right.  

In this zip file, I attached the modified script "ocsort_custom.py", pictures with the settings I used for OC-SORT and the evaluation results using the official eval code. I placed the folder "MOT20-train" under datasets and wrote to a file named "output." 

I ran this from the root folder...
python ocsort_custom.py --raw_results_path datasets/MOT20-train --hp --dataset MOT20-train --out_path output

[Archive.zip](https://github.com/noahcao/OC_SORT/files/8457284/Archive.zip)

**Comment by noahcao** [comment]
Hi,

thanks for using OC-SORT. As the comments at the very beginning of file [run_ocsort_public.py](https://github.com/noahcao/OC_SORT/blob/master/tools/run_ocsort_public.py) indicate, this file is not used to directly reproduce the MOT17-public and MOT20-public results reported in the paper because on these two benchmarks, people use a detection filtering technique as a common practice.

But still, even considering that, the scores you get directly on MOT20-train are still lower than I would expect. Have you tried that on CroHD (headtrack) or KITTI first or double check the detection files? If you confirm they are all right but still get the such results on MOT20-train, I will later try to check back afterwards.

**Comment by noahcao** [comment]
I gave a rough look into the detection files and the output files. A significant issue is the loss of objects.

For example, on the 7th frame of MOT20-01, there are in total ~30 detections but only ~10 show in the final output tracking results. I am not sure if that can be improved if you use a lower IoU threshold during association for debug first?

**Comment by JLJ19** [comment]
Ah thanks, that gave me an idea.  I lowered the det_thresh to -0.1 so that all detections were included.  With that change, now I am getting HOTA=41.8 and MOTA=50.0 combined scores.  So I am guessing that the detection filtering is what gives you the extra boost in the paper.  Any chance you could share filtered public detection files for MOT20 train/test sets?  I have my own tracker (CT_v0 on MOT20) and would love to compare using the exact same data source.

**Comment by noahcao** [comment]
Hi,

In the beginning of that script, I commented with a codeline from CenterTrack. You can add the filtering same as it does by the YOLOX detector for private tracking (though by default I use IoU>=0.3 for filtering). I will upload my code for public tracking and the result detections once I have cleaned up that part of code.

Thank you very much for sharing your findings!
